repository: lq8 / www.lq8.net
repository_url: https://dh.lq8.net/

timezone: Asia/Handan
lang: zh_CN

title: 678导航·简洁有用的导航
alias_en: 678
alias_cn: 678导航
description: 世界的创新源于学术的探索•学术导航
keywords: 678, 导航, 678导航, 学术导航, scholar, 678-Navi, 678, HEBART, 678, Navigation
url: https://dh.lq8.net
url: https://dh.lq8.net
established_at: "2018-07-07T00:00+08:00"


author: 678
author_url: https://dh.lq8.net
organization: 678
organization_url: https://dh.lq8.net
contact: lq8.net

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor

encoding: UTF-8

theme: jekyll-theme-cayman
