repository: anyi98 / anyi98.github.io
repository_url: https://github.com/anyi98/anyi98.github.io

timezone: Asia/beijing
lang: zh_CN

标题：安逸导航
alias_en：BYR-Navi
alias_cn: 北邮人导航
描述：一个导航网站
关键词;导航安逸导航北邮人导航
网址：HTTPS：//anyi98.github.io
established_at ：“2016-10-01T00：00 + 08:00”

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
